#!/usr/bin/env bash

docker run -m 2g --rm -v $(pwd):/home/circleci/repo -v /tmp/gradleDocker:/home/circleci/.gradle -w="/home/circleci/repo" starcoin/sirius:buildv2 ./gradlew --no-daemon --max-workers 2 $@
